github: [nitraglobal]
patreon: nitraglobal
custom:
  - "https://x.com/nitraglobal"
  - "https://instagram.com/nitraglobal"
  - "https://tiktok.com/@nitra.global"
  - "https://youtube.com/@nitraglobal"
  - "https://nitraglobal.wixsite.com/nitra-global"
